# Generated by Django 5.2.7 on 2025-12-14 00:39

from django.db import migrations
from django.utils.text import slugify

PRESET_CATEGORIES = [
    "Furniture",
    "Electronics",
    "Textbooks",
    "Housing & Moving",
    "Clothing",
    "Kitchen",

    "Appliances",
    "Bicycles & Transportation",
    "Dorm Essentials",
    "Home Decor",
    "Office & Study Supplies",
    "Sports & Fitness",
    "Musical Instruments",
    "Gaming & Consoles",
    "Tickets & Events",
    "Free Stuff",

    "Miscellaneous",
]

def seed_categories(apps, _schema_editor):
    Category = apps.get_model("listings", "Category")

    for name in PRESET_CATEGORIES:
        slug = slugify(name)

        # Ensure uniqueness manually
        base_slug = slug
        i = 2
        while Category.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{i}"
            i += 1

        Category.objects.get_or_create(
            name=name,
            defaults={"slug": slug},
        )

class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_categories),
    ]
